#!/usr/bin/env bash
# install.sh — interactive one-shot installer for self-hosted ndn-rs.
#
# Usage (from a fresh VPS with docker installed):
#   curl -fsSL https://raw.githubusercontent.com/named-data/ndn-rs/main/deploy/install.sh | bash
#
# Or local-checkout:
#   bash deploy/install.sh
#
# Idempotent: re-running it refreshes the config from your answers and
# `docker compose up -d`s. Existing volumes (PIB, ACME cache) are
# preserved.

set -euo pipefail

# ── Locate the deploy/ dir ───────────────────────────────────────────────────
# When run via `curl | bash`, $0 is /dev/stdin — fall back to the
# current working directory and download the supporting files.

if [[ -f "$(dirname "${BASH_SOURCE[0]:-}")/docker-compose.yml" ]]; then
  DEPLOY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
else
  DEPLOY_DIR="${PWD}/ndn-rs-deploy"
  mkdir -p "$DEPLOY_DIR"
  echo "[install] downloading deploy assets to ${DEPLOY_DIR}"
  base="https://raw.githubusercontent.com/named-data/ndn-rs/main/deploy"
  for f in docker-compose.yml ndn-fwd.example.toml backup.sh; do
    curl -fsSL "${base}/${f}" -o "${DEPLOY_DIR}/${f}"
  done
  chmod +x "${DEPLOY_DIR}/backup.sh"
fi

cd "$DEPLOY_DIR"

# ── Prerequisite checks ──────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  echo "[install] FATAL: docker not found. Install Docker first:"
  echo "          https://docs.docker.com/engine/install/"
  exit 1
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "[install] FATAL: 'docker compose' v2 plugin missing. Install:"
  echo "          https://docs.docker.com/compose/install/"
  exit 1
fi

# ── Interactive prompts ──────────────────────────────────────────────────────
# Each prompt accepts a default in brackets; press Enter to take it.

prompt() {
  local var="$1" question="$2" default="${3:-}"
  local current="${!var:-}"
  local current_or_default="${current:-${default}}"
  local prefix=""
  if [[ -n "${current_or_default}" ]]; then
    prefix=" [${current_or_default}]"
  fi
  read -r -p "${question}${prefix}: " response </dev/tty
  printf -v "$var" "%s" "${response:-${current_or_default}}"
}

echo
echo "ndn-rs self-hosting setup."
echo "I'll ask four questions, write a config, and bring up the stack."
echo

prompt DOMAIN       "Your domain (FQDN you control)"                "ndn.example.com"
prompt EMAIL        "Email address for ACME (Let's Encrypt) account" ""
prompt DNS_PROVIDER "DNS provider (cloudflare, route53, manual)"    "cloudflare"
# Reverse-DNS default for the NDN namespace.
default_ns="/$(echo "$DOMAIN" | awk -F. '{ for (i=NF; i>0; i--) printf "/%s", $i }' | sed 's|^/||')"
default_ns="${default_ns//.\//.\/}"  # noop, kept for readability
prompt NAMESPACE    "Your NDN namespace prefix"                     "${default_ns}"

if [[ -z "$EMAIL" ]]; then
  echo "[install] FATAL: ACME requires an email. Re-run and supply one."
  exit 1
fi

# ── Provider-specific credentials ────────────────────────────────────────────
if [[ "$DNS_PROVIDER" == "cloudflare" ]]; then
  prompt CLOUDFLARE_API_TOKEN "Cloudflare API token (DNS:Edit on the zone)" "${CLOUDFLARE_API_TOKEN:-}"
  prompt CLOUDFLARE_ZONE_ID   "Cloudflare zone id"                          "${CLOUDFLARE_ZONE_ID:-}"
  if [[ -z "${CLOUDFLARE_API_TOKEN}" || -z "${CLOUDFLARE_ZONE_ID}" ]]; then
    echo "[install] WARNING: Cloudflare credentials empty. ACME will fail until you supply them via the .env file."
  fi
fi

# ── Materialize ndn-fwd.toml ─────────────────────────────────────────────────
echo "[install] writing ndn-fwd.toml from ndn-fwd.example.toml"
sed \
  -e "s|you@example.com|${EMAIL}|g" \
  -e "s|ndn\\.example\\.com|${DOMAIN}|g" \
  -e "s|/com/example/ndn|${NAMESPACE}|g" \
  -e "s|cloudflare|${DNS_PROVIDER}|g" \
  ndn-fwd.example.toml > ndn-fwd.toml

# ── Materialize .env for compose-time substitution ──────────────────────────
cat > .env <<EOF
# Generated by deploy/install.sh — re-run install.sh to refresh.
NDN_FWD_TAG=v0-stable
NDN_RELAY_TAG=v0-stable
NDN_FWD_LOG=info

# Cloudflare ACME credentials (consumed by the toml's \${} substitutions).
CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN:-}
CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID:-}
EOF
chmod 600 .env

echo
echo "[install] config written:"
echo "          ${DEPLOY_DIR}/ndn-fwd.toml"
echo "          ${DEPLOY_DIR}/.env"
echo

# ── Bring up the stack ──────────────────────────────────────────────────────
read -r -p "Start the stack now with 'docker compose up -d'? [Y/n] " yn </dev/tty
yn="${yn:-Y}"
if [[ "$yn" =~ ^[Yy]$ ]]; then
  docker compose up -d
  echo
  echo "[install] stack is up. Useful next commands:"
  echo "          docker compose logs -f ndn-fwd"
  echo "          docker compose ps"
  echo "          ./backup.sh > ndn-fwd-backup.tar.gz   # cron-friendly"
  echo
  echo "[install] auto-update is OPT-IN. Enable with:"
  echo "          docker compose --profile watchtower up -d"
else
  echo "[install] skipped 'docker compose up'. Run it manually when ready."
fi
